Adding noise reduction

diff --git a/videocli b/videocli
--- a/videocli
+++ b/videocli
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Tests for requirements
+ffmpeg -version >/dev/null || { echo >&2 "We require 'ffmpeg' but it's not installed. Install it by 'sudo apt-get install ffmpeg' Aborting."; exit 1; }
+
 set -e
 export VIDEOCLI_WORKDIR=$(cd $(dirname $0) && pwd)
 export VIDEOCLI_LOGDIR=${VIDEOCLI_WORKDIR}/.logs
@@ -33,6 +36,10 @@ case "$1" in
   concat)
     shift
     "$VIDEOCLI_WORKDIR/commands/concat" "$@" | tee -ia "$VIDEOCLI_LOGDIR/concat_last.log"
+    ;;
+  noise-reduction)
+    shift
+    "$VIDEOCLI_WORKDIR/commands/noise_reduction" "$@" | tee -ia "$VIDEOCLI_LOGDIR/noise_reduction_last.log"
     ;;
   *)
     cli_help
